# Onwards Gateway ServiceMonitor
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inference-stack.fullname" . }}-onwards
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "inference-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: onwards
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "inference-stack.onwards.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
    {{- if .Values.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml .Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.serviceMonitor.bearerTokenSecret }}
    bearerTokenSecret:
      {{- toYaml .Values.serviceMonitor.bearerTokenSecret | nindent 6 }}
    {{- end }}
{{- end }}

---
# Model Group ServiceMonitors
{{- if .Values.serviceMonitor.enabled }}
{{- range $groupName, $group := .Values.modelGroups }}
{{- if $group.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "inference-stack.fullname" $ }}-{{ $groupName }}
  {{- if $.Values.serviceMonitor.namespace }}
  namespace: {{ $.Values.serviceMonitor.namespace }}
  {{- else }}
  namespace: {{ $.Release.Namespace }}
  {{- end }}
  labels:
    {{- include "inference-stack.labels" $ | nindent 4 }}
    app.kubernetes.io/component: model-group
    app.kubernetes.io/model-group: {{ $groupName }}
    {{- with $.Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "inference-stack.modelGroup.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/model-group: {{ $groupName }}
  endpoints:
  - port: http
    interval: {{ $.Values.serviceMonitor.interval }}
    scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
    {{- if $.Values.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml $.Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
    {{- if $.Values.serviceMonitor.bearerTokenSecret }}
    bearerTokenSecret:
      {{- toYaml $.Values.serviceMonitor.bearerTokenSecret | nindent 6 }}
    {{- end }}
  {{- if and $group.additionalPorts (gt (len $group.additionalPorts) 0) }}
  {{- range $port := $group.additionalPorts }}
  {{- if eq $port.name "metrics" }}
  - port: {{ $port.name }}
    interval: {{ $.Values.serviceMonitor.interval }}
    scrapeTimeout: {{ $.Values.serviceMonitor.scrapeTimeout }}
    path: /metrics
    {{- if $.Values.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml $.Values.serviceMonitor.tlsConfig | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}